name: Create Welcome Issue
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  create_welcome_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create welcome issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              labels: "welcome"
            });
            
            if (issues.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: "🚀 Welcome to DESN368 - Start Here!",
                labels: ["welcome"],
                body: `## Welcome to your portfolio repository!

Complete your [setup checklist](setup/ONBOARDING-CHECKLIST.md) to get started.

### Next Steps:
1. Follow the setup checklist
2. Update your README with your profile links  
3. Submit to Canvas when complete

Close this issue when you're done!`
              });
              console.log("✅ Welcome issue created!");
            } else {
              console.log("👋 Welcome issue already exists");
            }
