# .github/workflows/create-welcome-issue.yml
name: Create Welcome Issue
on:
  workflow_run:
    workflows: ["Bootstrap Workflow"]
    types:
      - completed

permissions:
  contents: write
  issues: write

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Check if issue already exists
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open"
            });
            const exists = issues.some(issue => issue.title === "👋 Welcome!");
            
            if (!exists) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: "👋 Welcome!",
                body: "Thanks for accepting the assignment! Please follow the instructions here..."
              });
            } else {
              console.log("👋 Welcome issue already exists. Skipping.");
            }
