name: Setup Progress Tracker
on:
  push:
    paths: 
      - 'setup/ONBOARDING-CHECKLIST.md'
      - 'README.md'
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  track_progress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check setup progress
        id: check-progress
        run: |
          if [ -f "setup/ONBOARDING-CHECKLIST.md" ]; then
            COMPLETED=$(grep -c '\[x\]' setup/ONBOARDING-CHECKLIST.md || echo "0")
            TOTAL=$(grep -c '\[ \]\|\[x\]' setup/ONBOARDING-CHECKLIST.md || echo "1")
          else
            COMPLETED=0
            TOTAL=1
          fi
          
          echo "completed=$COMPLETED" >> $GITHUB_OUTPUT
          echo "total=$TOTAL" >> $GITHUB_OUTPUT
          echo "✅ Setup Progress: $COMPLETED/$TOTAL tasks completed"
          
      - name: Celebrate progress
        if: steps.check-progress.outputs.completed >= 1
        run: |
          echo "🎉 Great job! You've completed ${{ steps.check-progress.outputs.completed }} setup task(s)!"
          
      - name: Add completion badge
        if: steps.check-progress.outputs.completed >= 4
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "all",
              labels: "completed"
            });
            
            const completionIssue
