name: Student Setup Verification
on:
  push:
    paths: 
      - 'setup/ONBOARDING-CHECKLIST.md'
      - 'README.md'
  workflow_dispatch: # Allows manual triggering

jobs:
  verify-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Check setup progress
        id: check-progress
        run: |
          # Count completed checkboxes in checklist
          COMPLETED=$(grep -c '\[x\]' setup/ONBOARDING-CHECKLIST.md || echo "0")
          TOTAL=$(grep -c '\[ \]\|\[x\]' setup/ONBOARDING-CHECKLIST.md || echo "1")
          
          echo "completed=$COMPLETED" >> $GITHUB_OUTPUT
          echo "total=$TOTAL" >> $GITHUB_OUTPUT
          echo "Setup Progress: $COMPLETED/$TOTAL tasks completed"
          
      - name: Enable GitHub Pages
        if: steps.check-progress.outputs.completed >= 3
        run: |
          echo "🚀 Setup nearly complete! GitHub Pages will be enabled."
          # Note: Actual Pages enablement requires API token with admin rights
          
      - name: Create completion badge
        if: steps.check-progress.outputs.completed >= 4
        run: |
          echo "🎉 Setup Complete!"
          echo "Student has completed ${{ steps.check-progress.outputs.completed }}/${{ steps.check-progress.outputs.total }} setup tasks"
          
      - name: Update portfolio README
        if: steps.check-progress.outputs.completed >= 4
        run: |
          # Add completion badge to README if not already present
          if ! grep -q "Setup Complete" README.md; then
            sed -i '1i ![Setup Complete](https://img.shields.io/badge/Setup-Complete-green)' README.md
            echo "Added completion badge to README"
          fi
